config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :employee_profiles do
    collection do
      get :dashboard
      get :order_history
      get :favourite_order
    end
  end

  resources :chef_profiles do
    collection do
      get :dashboard
      get :orders
      get :gallery
    end
    
    member do
      get :order_update
      patch :order_update
    end
  end

  resources :user_profiles do
    collection do
      get :dashboard
      get :order_history
      get :favourite_order
    end
  end

  resources :companies
  resources :users, except: [:new]
  resources :food_stores
  resources :food_items
  resources :food_categories
  resources :reviews


  get    "signup", to: "users#new"
  get    "login" , to: "sessions#new"
  post   "login" , to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "auth/facebook/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")

  get "dashboard",    to: "admins#dashboard"
  get "admin/orders", to: "admins#orders"
  get "order/:id/approve", to: "admins#approve_order", as: "approve_order"
  get "chef/:id/approve",     to: "admins#approve_chef", as: "approve_chef"
  get "employee/:id/approve", to: "admins#approve_employee", as: "approve_employee"
  get "chef/:id/reject",     to: "admins#reject_chef", as: "reject_chef"
  get "employee/:id/reject", to: "admins#reject_employee", as: "reject_employee"
  get "store/:id", to: "admins#hide_store", as: "store_indexing_toggle"
  get "admin/credits", to: "admins#provide_credits", as: "admin_credit"

  get "error", to: "pages#show"
  get "notification", to: "pages#notification"
  get "notification/clear", to: "pages#delete_notifications"
  get "reset", to: "pages#reset_filters"

  get "messages/index"
  post "messages/create"
  
  post   "carts/add"
  get    "cart",   to: "carts#show"
  get    "orders", to: "carts#order_show", as: "order_show"
  get    "cart/:id/reorder", to: "carts#reorder", as: "reorder_cart"
  get    "cart/:id/favourite", to: "carts#set_favourite", as: "set_favourite"
  patch  "cart_item/:id/update", to: "cart_items#update", as: "item_update"
  patch  "order", to: "carts#order", as: "cart_order"
  delete "cart_item/:id", to: "cart_items#delete", as: "item_delete"  
end

app/views/admins/dashboard.html.erb
<h3><i class="fa fa-home" aria-hidden="true"></i> Admin Dashboard </h3>

<hr/>

<div class="row d-flex justify-content-center">
  <div class="card col-md-3 col-xs-12  m-2 p-0">
    <div class="card-body">
      <h5 class="card-title">Employee Confirmation</h5>
      <p class="card-text text-muted">Section to accept employees and grant them priority while placing orders on the application.</p>  
    </div>

    <div class="card-footer">
      <%= link_to "Approve", employee_profiles_path, class: "btn btn-primary", title: "Approve Employees" %>
    </div>
  </div>

  <div class="card col-md-3 col-xs-12 m-2 p-0">
    <div class="card-body">
      <h5 class="card-title">Chef Confirmation</h5>
      <p class="card-text text-muted">Section to approve Chefs of respective food store so that they can create food items available to order.</p>
    </div>

    <div class="card-footer">
      <%= link_to "Approve", chef_profiles_path, class: "btn btn-primary", title: "Approve Chefs" %>
    </div>
  </div>

  <div class="card col-md-3 col-xs-12 m-2 p-0">
    <div class="card-body">
      <h5 class="card-title">Manage Companies</h5>
      <p class="card-text text-muted">Section to add or remove companies belonging to the app.</p>
    </div>

    <div class="card-footer">
      <%= link_to "Manage", companies_path, class: "btn btn-primary", title: "Manage Companies" %>
    </div>
  </div>

  <div class="card col-md-3 col-xs-12 m-2 p-0">
    <div class="card-body">
      <h5 class="card-title">Food Stores</h5>
      <p class="card-text text-muted">Section to add or remove Food Stores, also hide order button.</p>
    </div>

    <div class="card-footer">
      <%= link_to "Manage", food_stores_path, class: "btn btn-primary", title: "Mange Food Stores" %>
    </div>
  </div>

  <div class="card col-md-3 col-xs-12 m-2 p-0">
    <div class="card-body">
      <h5 class="card-title">Store Category</h5>
      <p class="card-text text-muted">Section to add or remove Store Category</p>        
    </div>

    <div class="card-footer">
      <%= link_to "Manage", food_categories_path, class: "btn btn-primary", title: "Mange Food Categories" %>
    </div>
  </div>

  <div class="card col-md-3 col-xs-12 m-2 p-0">
    <div class="card-body">
      <h5 class="card-title">Confirm orders</h5>
      <p class="card-text text-muted">Section to confirm orders placed in the app</p>        
    </div>
    
    <div class="card-footer">
      <%= link_to "Manage Orders", admin_orders_path, class: "btn btn-primary", title: "Mange Orders" %>
    </div>
  </div>

  <div class="card col-md-3 col-xs-12 m-2 p-0">
    <div class="card-body">
      <h5 class="card-title">Credits</h5>
      <p class="card-text text-muted">Section to provide credits to users</p>        
    </div>
    
    <div class="card-footer">
      <%= link_to "Manage Credits", admin_credit_path, class: "btn btn-primary", title: "Mange credits" %>
    </div>
  </div>
</div>

app/views/admins/order.html.erb
<h3>Listing all orders</h3>
<hr/>
<div class="col-8 offset-2">
  <table class="table table-borderless">
    <thead>
      <tr>
        <th>Order No:</th>
        <th>Order status</th>
        <th>Placed by</th>
        <th>Food Store</th>
        <th>Bill Amount</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% i=0 %>
    <% @orders.each do |order|%>
      <% if order.user.employee? %>
        <tr>
          <td><%= i = i+1 %></td>
          <td><%= order.order_status %></td>
          <td><%= order.user.role %> </td>
          <td><%= order.store.name %></td>
          <td><%= order.total%> </td>
          <td>
            <%= link_to "details", order_show_path(order.id) %> | 
            <%= link_to "approve", approve_order_path(order.id) %>
          </td>
        </tr>  
      <% end %>              
    <% end %>
    <% @orders.each do |order|%>
      <% if !order.user.employee? %>
        <tr>
          <td><%= i = i+1 %></td>
          <td><%= order.order_status %></td>
          <td><%= order.user.role %> </td>
          <td><%= order.store.name %></td>
          <td><%= order.total%> </td>
          <td>
            <%= link_to "details", order_show_path(order.id) %> | 
            <%= link_to "approve", approve_order_path(order.id) %>
          </td>
        </tr>  
      <% end %>              
    <% end %>
    </tbody>
  </table>
</div>

app/views/admins/orders.html.erb
<h3>Listing all orders</h3>

<hr/>

<div class="col-8 offset-2">
  <div class="card p-4">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>Order No:</th>
          <th>Order status</th>
          <th>Placed by</th>
          <th>Food Store</th>
          <th>Bill Amount</th>
          <th>Actions</th>
        </tr>
      </thead>
  
      <tbody>
      <% i=0 %>
      <% @orders.each do |order|%>
        <% if order.user.employee? %>
          <tr>
            <td><%= i = i+1 %></td>
            <td><%= order.order_status %></td>
            <td><%= order.user.role %> </td>
            <td><%= order.store.name %></td>
            <td><%= order.total%> </td>
            <td>
              <%= link_to "details", order_show_path(order.id) %> | 
              <%= link_to "approve", approve_order_path(order.id) %>
            </td>
          </tr>  
        <% end %>              
      <% end %>
      
      <% @orders.each do |order|%>
        <% if !order.user.employee? %>
          <tr>
            <td><%= i = i+1 %></td>
            <td><%= order.order_status %></td>
            <td><%= order.user.role %> </td>
            <td><%= order.store.name %></td>
            <td><%= order.total%> </td>
            <td>
              <%= link_to "details", order_show_path(order.id) %> | 
              <%= link_to "approve", approve_order_path(order.id) %>
            </td>
          </tr>  
        <% end %>              
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/provide_credits.html.erb
<div class="card p-4 mb-3 col-8 offset-2">
  <h3><i class="fa fa-check-square-o" aria-hidden="true"></i> Employees</h3>

  <hr>

  <table class="table table-borderless">
    <thead>
      <tr>
        <th>S.No:</th>
        <th>Employee Name</th>
        <th>Credit</th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each_with_index do |employee,i|%>
        <tr>
          <td><%= i+1 %></td>
          <td><%= employee.name %></td>
          <td>
            <%= form_for employee, url: employee_profile_path(employee.id) do |f| %>  
              <%= f.number_field :credit, value: employee.credit ? '%.2f' % employee.credit : nil, min: 0, step: 0.01, for: "credit", class: "form-control", autocomplete: "credit", placeholder: "Enter credit", required: true %>
              <%= button_tag type: 'submit', class: "btn btn-secondary px-3", title: "Update Cart" do %>
                <i class="fa fa-check" aria-hidden="true"></i> Update
              <% end %>
            <% end %> 
          </td>
        </tr>      
      <% end %>
    </tbody>
  </table>    
</div>

<div class="card p-4 col-8 offset-2">
  <h3><i class="fa fa-check-square-o" aria-hidden="true"></i> Users</h3>

  <hr>

  <table class="table table-borderless">
    <thead>
      <tr>
        <th>S.No:</th>
        <th>User Name</th>
        <th>Credit</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each_with_index do |user,i|%>
        <tr>
          <td><%= i+1 %></td>
          <td><%= user.name %></td>          
          <td>
            <%= form_for user, url: user_profile_path(user.id) do |f| %>
              <%= f.number_field :credit, value: user.credit ? '%.2f' % user.credit : nil, min: 0, step: 0.01, for: "credit", class: "form-control", autocomplete: "credit", placeholder: "Enter credit", required: true %>
              <%= button_tag type: 'submit', class: "btn btn-secondary px-3", title: "Update Cart" do %>
                <i class="fa fa-check" aria-hidden="true"></i> Update
              <% end %>
            <% end %>
          </td>
        </tr>      
      <% end %>
    </tbody>
  </table>    
</div>