config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :employee_profiles do
    collection do
      get :dashboard
      get :order_history
      get :favourite_order
    end
  end

  resources :chef_profiles do
    collection do
      get :dashboard
      get :orders
      get :gallery
    end
    
    member do
      get :order_update
      patch :order_update
    end
  end

  resources :user_profiles do
    collection do
      get :dashboard
      get :order_history
      get :favourite_order
    end
  end

  resources :companies
  resources :users, except: [:new]
  resources :food_stores
  resources :food_items
  resources :food_categories
  resources :reviews


  get    "signup", to: "users#new"
  get    "login" , to: "sessions#new"
  post   "login" , to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "auth/facebook/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")

  get "dashboard",    to: "admins#dashboard"
  get "admin/orders", to: "admins#orders"
  get "order/:id/approve", to: "admins#approve_order", as: "approve_order"
  get "chef/:id/approve",     to: "admins#approve_chef", as: "approve_chef"
  get "employee/:id/approve", to: "admins#approve_employee", as: "approve_employee"
  get "chef/:id/reject",     to: "admins#reject_chef", as: "reject_chef"
  get "employee/:id/reject", to: "admins#reject_employee", as: "reject_employee"
  get "store/:id", to: "admins#hide_store", as: "store_indexing_toggle"
  get "admin/credits", to: "admins#provide_credits", as: "admin_credit"

  get "error", to: "pages#show"
  get "notification", to: "pages#notification"
  get "notification/clear", to: "pages#delete_notifications"
  get "reset", to: "pages#reset_filters"

  get "messages/index"
  post "messages/create"
  
  post   "carts/add"
  get    "cart",   to: "carts#show"
  get    "orders", to: "carts#order_show", as: "order_show"
  get    "cart/:id/reorder", to: "carts#reorder", as: "reorder_cart"
  get    "cart/:id/favourite", to: "carts#set_favourite", as: "set_favourite"
  patch  "cart_item/:id/update", to: "cart_items#update", as: "item_update"
  patch  "order", to: "carts#order", as: "cart_order"
  delete "cart_item/:id", to: "cart_items#delete", as: "item_delete"  
end

app/models/food_store.rb
class FoodStore < ApplicationRecord 
  belongs_to :food_category
  has_many   :food_items,    dependent: :destroy
  has_many   :chef_profiles, dependent: :destroy  
  has_many   :carts, dependent: :destroy

  validates :name, presence: true, length: { maximum: 40, minimum: 2 }, uniqueness: true 

  def chefs
    ChefProfile.where(food_store_id: self.id)
  end

end

app/controllers/food_stores_controller.rb
class FoodStoresController < ApplicationController
  before_action :validate_admin
  
  def index
    @stores = FoodStore.all
  end

  def new
    @store = FoodStore.new
    @category = FoodCategory.all
  end

  def create
    @store = FoodStore.new(store_params)
    return redirect_to food_stores_path, flash: { success: ("FoodStore was succesfully created!") } if @store.save  
    render 'new'
  end

  def edit
    @store = FoodStore.find(params[:id])
    @category = FoodCategory.all
  end

  def update
    @store = FoodStore.find(params[:id])
    
    if @store.update(store_params)
      flash[:success] = "FoodStore was succesfully Updated!"
      redirect_to food_stores_path
    else
      flash[:warning] = "#{store.errors.full_messages}"
      render 'edit'
    end
  end

  def destroy
    store = FoodStore.find(params[:id])
    store.destroy
    flash[:danger] = " FoodStore #{store.name} was deleted."
    redirect_to food_stores_path
  end

  private
  
  def store_params
    params.require(:food_store).permit(:name, :food_category_id)
  end
end

app/views/food_stores/_form.html.erb
<%= form_for @store do |form| %>
  <div class="col-8 mx-auto">    
    <div class="card">
      <div class="card-header text-center">
        <h3><%= yield(:card_header) %></h3>
      </div>

      <div class="card-body text-right">
        <%= render 'layouts/error', obj: @store %>
        <div class="form-group row">
          <%= form.label :name, for: "name", class:"col-sm-4 col-form-label"%>
          <div class="col-sm-6">
            <%= form.text_field :name, for: "name", class: "form-control", autofocus: true, autocomplete: "name", placeholder: "Enter Food Store name", required: true %>
          </div>
        </div> 

        <div class="form-group row">
        <%= form.label :food_category, for: "food_category", class:"col-sm-4 col-form-label", autocomplete: "food_category"  %>
        <div class="col-sm-2 my-2">
          <%= form.select(:food_category_id) do %>
            <% @category.each do |c| -%>
              <%= content_tag(:option, c.name, value: c.id) %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>    
  </div>

  <div class="row justify-content-center my-4"> 
    <div class="col-2">
      <strong><%= form.submit( yield(:button_text),{ class: "btn btn-primary btn-md btn-block", data:{disable_with: "saving..."}})%></strong>
    </div>
  </div>  
<% end %>

app/views/food_stores/edit.html.erb
<% provide(:card_header, "Edit Food Store")%>
<% provide(:button_text, "Update")%>
<%= render "form" %>

app/views/food_stores/index.html.erb
<div class="card p-4 col-6 offset-3">
  <h3><i class="fa fa-cutlery" aria-hidden="true"></i> Food Stores</h3>

  <hr/>

  <table class="table table-borderless">
    <thead>
      <tr>
        <th>S.No:</th>
        <th>Food Store Name</th>
        <th>Actions</th>
        <th>Order Hide/Show</th>
      </tr>
    </thead>

    <tbody>
      <% @stores.each_with_index do |store,i|%>
        <tr>
          <td><%= i+1 %></td>
          <td><%= store.name %></td>
          <td>
            <%= edit_link(edit_food_store_path(store.id)) %>
            <%= delete_link(food_store_path(store.id)) %>
          </td>
          <td>
            <% if store.indexing %>
              <%= link_to "Hide Order Button", store_indexing_toggle_path(store.id), class: "btn btn-sm btn-secondary px-3" %>            
            <% else %>
              <%= link_to "Show Order Button", store_indexing_toggle_path(store.id), class: "btn btn-sm btn-success px-3" %>            
            <% end %>
          </td>
        </tr>      
      <% end %>
    </tbody>
  </table>

  <hr/>
  
  <div class="text-center">
    <%= link_to "New Food Store", new_food_store_path, class: "btn btn-primary px-3", title: "add new food store" %>
  </div>
</div>

app/views/food_stores/new.html.erb
<% provide(:card_header, "Create New Food Store")%>
<% provide(:button_text, "Save")%>
<%= render "form" %>