config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :employee_profiles do
    collection do
      get :dashboard
      get :order_history
      get :favourite_order
    end
  end

  resources :chef_profiles do
    collection do
      get :dashboard
      get :orders
      get :gallery
    end
    
    member do
      get :order_update
      patch :order_update
    end
  end

  resources :user_profiles do
    collection do
      get :dashboard
      get :order_history
      get :favourite_order
    end
  end

  resources :companies
  resources :users, except: [:new]
  resources :food_stores
  resources :food_items
  resources :food_categories
  resources :reviews


  get    "signup", to: "users#new"
  get    "login" , to: "sessions#new"
  post   "login" , to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "auth/facebook/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")

  get "dashboard",    to: "admins#dashboard"
  get "admin/orders", to: "admins#orders"
  get "order/:id/approve", to: "admins#approve_order", as: "approve_order"
  get "chef/:id/approve",     to: "admins#approve_chef", as: "approve_chef"
  get "employee/:id/approve", to: "admins#approve_employee", as: "approve_employee"
  get "chef/:id/reject",     to: "admins#reject_chef", as: "reject_chef"
  get "employee/:id/reject", to: "admins#reject_employee", as: "reject_employee"
  get "store/:id", to: "admins#hide_store", as: "store_indexing_toggle"
  get "admin/credits", to: "admins#provide_credits", as: "admin_credit"

  get "error", to: "pages#show"
  get "notification", to: "pages#notification"
  get "notification/clear", to: "pages#delete_notifications"
  get "reset", to: "pages#reset_filters"

  get "messages/index"
  post "messages/create"
  
  post   "carts/add"
  get    "cart",   to: "carts#show"
  get    "orders", to: "carts#order_show", as: "order_show"
  get    "cart/:id/reorder", to: "carts#reorder", as: "reorder_cart"
  get    "cart/:id/favourite", to: "carts#set_favourite", as: "set_favourite"
  patch  "cart_item/:id/update", to: "cart_items#update", as: "item_update"
  patch  "order", to: "carts#order", as: "cart_order"
  delete "cart_item/:id", to: "cart_items#delete", as: "item_delete"  
end

app/models/cart.rb
class Cart < ApplicationRecord
  enum order_status: [:Placed, :Recieved, :Cooking, :Delivered]

  belongs_to :user
  belongs_to :food_store, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :food_items, through: :cart_items
  has_one :review, dependent: :destroy

  scope :to_approve,       -> { where(order_status: 0) }
  scope :live_orders,      -> { where(order_status: 1..2) }
  scope :active_orders,    -> { where(order_status: 0..2) }
  scope :delivered_orders, -> { where(order_status: 3) }

  def total
    cart_items.collect {|item| item.valid? ? item.sub_total : 0}.sum
  end

  def store
    food_items.first.food_store
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add
    cart_item = current_cart.cart_items.new(cart_items_params)

    if same_food_store
      if cart_item.save
        flash[:success] = "Item Added to Cart"
        redirect_to root_path
      else
        flash[:danger] = "Food Item already in the cart"
        redirect_to root_path
      end
    else
      flash[:warning] = "Clear cart first to add items from different store!"
      redirect_to root_path
    end
  end

  def show
    @cart_items = current_cart.cart_items
  end

  def order
    check_cart
    
    if current_user.carts.active_orders.count == 0    
      if current_cart.update cart_params
        flash[:success] = "Order placed Successfully!"

        if current_cart.total > 300
          current_user.user_profile.update(credit: current_user.user_profile.credit*0.8) if current_user.user?
          current_user.employee_profile.update(credit: current_user.employee_profile.credit*0.8) if current_user.employee?
        end
        
        User.admins.each do |admin|
          Notification.create(user_id: admin.id, content: "You got new order to approve")
        end
        
        get_cart
        redirect_to order_show_path
      else
        flash[:danger] = "Something went wrong!"
        render cart_path
      end
    else
      flash[:warning] = "Please wait till last order is completed!"
      redirect_back(fallback_location: cart_path)
    end      
  end

  def reorder
    @cart = Cart.find params[:id]

    if current_user.carts.active_orders.count == 0  
      current_cart.cart_items.delete_all

      @cart.cart_items.each do |cart_item|
        current_cart.cart_items.create(food_item_id: cart_item.food_item.id, quantity: cart_item.quantity)
      end
      
      if current_cart.update(order_status: "Placed")
        flash[:success] = "Order placed Successfully!"

        if cart.total > 300
          current_user.user_profile.update(credit: current_user.user_profile.credit*0.8) if current_user.user? && current_user.user_profile.credit > 0 
          current_user.employee_profile.update(credit: current_user.employee_profile.credit*0.8) if current_user.employee? && current_user.employee_profile.credit > 0 
        end
        
        User.admins.each do |admin|
          Notification.create(user_id: admin.id, content: "You got new order to approve")
        end
        
        get_cart
        redirect_to order_show_path
      else
        flash[:danger] = "Something went wrong!"
        render cart_path
      end
    else
      flash[:warning] = "Please wait till last order is completed!"
      redirect_back(fallback_location: cart_path)
    end      
  end

  def order_show
    if current_user.admin?
      if params[:format]
        @current_order = Cart.find params[:format]
      else
        redirect_to error_path
      end
    else
      @carts = current_user.carts
      @past_orders   = @carts.delivered_orders
      @current_order = @carts.active_orders.first     
    end
  end

  def set_favourite
    @cart = Cart.find params[:id]
    @cart.toggle!(:favourite)
    if @cart.favourite
      flash[:success] = "Added to favourites"
    else
      flash[:danger] = "Removed from favourites"
    end

    redirect_to order_history_user_profiles_path if current_user.user?
    redirect_to order_history_employee_profiles_path if current_user.employee?
  end

  private

  def cart_params
    params.require(:cart).permit(:order_status, :food_store_id)
  end

  def cart_items_params
    params.require(:cart_item).permit(:food_item_id, :quantity)
  end

  def check_cart
    if current_cart.cart_items.count == 0
      flash[:danger] = "Add some food items in the cart first"
      redirect_to root_path
    end
  end
  
  # Ensures Cart Items From Same Food Store 
  def same_food_store
    unless @cart.cart_items.first.food_item.food_store.id == @cart.cart_items.last.food_item.food_store.id
      return false
    end
    true
  end

end

app/helpers/carts_helper.rb
module CartsHelper  

  def get_cart
    if current_user.carts.count > 0 && current_cart.order_status.nil?
      current_cart
    else
      set_cart
    end
  end

  def set_cart
    @cart = current_user.carts.create
  end

  def current_cart
    @cart ||= current_user.carts.last
  end 

  def active_order
    @active_order ||= current_user.carts.active_orders.first
  end
end

app/views/carts/order_show.html.erb
<% if @current_order %>
  <div class="col-8 offset-2">
    <div class="card p-4">
      <h4> Current Order Status: <strong class= "text-info"><%= @current_order.order_status %></strong></h4>
      <hr>

      <table class="table table-borderless">
        <thead>
          <tr>
            <th>S.No:</th>
            <th>Food Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Subtotal</th>
          </tr>
        </thead>

        <tbody>
        <% @current_order.cart_items.each_with_index do |item,i| %>
          <tr>
            <td><%= i+1 %></td>
            <td><%= item.food_item.name %></td>
            <td>Rs.<%= item.food_item.price %></td>
            <td><%= item.quantity %></td>
            <td>Rs.<%= item.sub_total %></td>
          </tr>      
        <% end %>
        </tbody>
      </table>    
    </div>    

    <hr/>
    
    <div class="d-flex justify-content-between">
      <div class="col-3"><p><strong>Total: Rs.<%= @current_order.total %></strong></p></div>
    </div> 
  </div>
<% else %>
  <hr/>
  <h3 class="text-center text-muted">No Active Order</h3>
<% end %>

app/views/carts/show.html.erb
<% if current_cart.cart_items.present? %>
  <div class="col-md-8 offset-md-2 col-sm-12">
    <div class="card p-4">
      <h3><i class="fa fa-shopping-cart" aria-hidden="true"></i> Cart</h3>
      <hr>

      <table class="table table-borderless">
        <thead>
          <tr>
            <th>S.No:</th>
            <th>Food Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Subtotal</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
        <% @cart_items.each_with_index do |item,i|%>
          <tr>
            <td><%= i+1 %></td>
            <td><%= item.food_item.name %></td>
            <td>Rs.<%= item.food_item.price %></td>
            <td>        
              <%= form_for item, url: item_update_path(item.id) do |f| %>
                <%= f.number_field :quantity, value: item.quantity, max:5, min:1 %>
                <%= button_tag type: 'submit', class: "btn btn-secondary btn-sm px-3", title: "Update Cart" do %>
                  <i class="fa fa-check" aria-hidden="true"></i>
                <% end %>
              <% end %>          
            </td>
            <td>Rs.<%= item.sub_total %></td>
            <td>
              <%= delete_link(item_delete_path(item.id)) %>
            </td>          
          </tr>      
        <% end %>
        </tbody>
      </table>    
    </div>
    
    <hr/>
    
    <div class="d-flex justify-content-between">
      <div class="col-5">
        <% if current_user.employee? %>
          <% if current_user.employee_profile.credit>0 && current_cart.total > 300 %>
            <p><strong>Total: Rs.<%= current_cart.total - (current_user.employee_profile.credit*0.2)  %><span> ( <%= current_user.employee_profile.credit*0.2  %> credits adjusted)</span></strong></p>
          <% else %>
            <p><strong>Total: Rs.<%= current_cart.total %></strong></p></div>
          <% end %>
        <% elsif current_user.user? %>
          <% if current_user.user_profile.credit>0 && current_cart.total > 300 %>
            <p><strong>Total: Rs.<%= current_cart.total - (current_user.user_profile.credit*0.2)  %></strong><span> ( <%= current_user.user_profile.credit*0.2  %> credits adjusted)</span></p>
          <% else %>
            <p><strong>Total: Rs.<%= current_cart.total %></strong></p></div>
          <% end %>
        <% end %>
      </div>

      <div class="col-3"> 
        <%= form_for current_cart, url: cart_order_path do |f| %>
          <%= f.hidden_field :order_status, value: "Placed" %>
          <%= f.hidden_field :food_store_id, value: current_cart.store.id %>
          <%= button_tag type: 'submit', class: "btn btn-success  px-4", title: "Place Order" do %>
            <i class="fa fa-credit-card" aria-hidden="true"></i> Order
          <% end %>
        <% end %>
      </div>
    </div> 
  </div>
<% else %>
  <h2 class="text-center text-muted">Add Some items to cart</h2>
<% end %>