config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :employee_profiles do
    collection do
      get :dashboard
      get :order_history
      get :favourite_order
    end
  end

  resources :chef_profiles do
    collection do
      get :dashboard
      get :orders
      get :gallery
    end
    
    member do
      get :order_update
      patch :order_update
    end
  end

  resources :user_profiles do
    collection do
      get :dashboard
      get :order_history
      get :favourite_order
    end
  end

  resources :companies
  resources :users, except: [:new]
  resources :food_stores
  resources :food_items
  resources :food_categories
  resources :reviews


  get    "signup", to: "users#new"
  get    "login" , to: "sessions#new"
  post   "login" , to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "auth/facebook/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")

  get "dashboard",    to: "admins#dashboard"
  get "admin/orders", to: "admins#orders"
  get "order/:id/approve", to: "admins#approve_order", as: "approve_order"
  get "chef/:id/approve",     to: "admins#approve_chef", as: "approve_chef"
  get "employee/:id/approve", to: "admins#approve_employee", as: "approve_employee"
  get "chef/:id/reject",     to: "admins#reject_chef", as: "reject_chef"
  get "employee/:id/reject", to: "admins#reject_employee", as: "reject_employee"
  get "store/:id", to: "admins#hide_store", as: "store_indexing_toggle"
  get "admin/credits", to: "admins#provide_credits", as: "admin_credit"

  get "error", to: "pages#show"
  get "notification", to: "pages#notification"
  get "notification/clear", to: "pages#delete_notifications"
  get "reset", to: "pages#reset_filters"

  get "messages/index"
  post "messages/create"
  
  post   "carts/add"
  get    "cart",   to: "carts#show"
  get    "orders", to: "carts#order_show", as: "order_show"
  get    "cart/:id/reorder", to: "carts#reorder", as: "reorder_cart"
  get    "cart/:id/favourite", to: "carts#set_favourite", as: "set_favourite"
  patch  "cart_item/:id/update", to: "cart_items#update", as: "item_update"
  patch  "order", to: "carts#order", as: "cart_order"
  delete "cart_item/:id", to: "cart_items#delete", as: "item_delete"  
end

app/models/food_category.rb
class FoodCategory < ApplicationRecord
  has_many :food_stores, dependent: :destroy 

  VALID_NAME_REGEX = /\A[\sA-Za-z]*\z/i

  validates :name,  presence: true, format: { with: VALID_NAME_REGEX }, length: { maximum: 40, minimum: 2 }, uniqueness: true
end

app/controllers/food_categories_controller.rb
class FoodCategoriesController < ApplicationController  
  before_action :validate_admin
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = FoodCategory.all
  end

  def new
    @category = FoodCategory.new
  end

  def create
    @category = FoodCategory.new(cat_params)
    if @category.save
      flash[:success] = "Category Added"
      redirect_to food_categories_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(cat_params)
      flash[:success] = "FoodCategory was succesfully Updated!"
      redirect_to food_categories_path
    else
      render "edit"
    end
  end

  def destroy
    @category.destroy
    flash[:danger] = " FoodCategory #{@category.name} was deleted."
    redirect_to food_categories_path
  end

  private

  def set_category
    @category = FoodCategory.find(params[:id])
  end
  
  def cat_params
    params.require(:food_category).permit(:name)
  end
end

app/views/food_categories/_form.html.erb
<%= form_for(@category) do |form| %>
  <div class="col-8 mx-auto">    
    <div class="card">
      <div class="card-header text-center">
        <h3><%= yield(:card_header) %></h3>
      </div>

      <div class="card-body text-right">
        <%= render "layouts/error", obj: @category %>
        <div class="form-group row">
          <%= form.label :name, for: "name", class:"col-sm-4 col-form-label"%>
          <div class="col-sm-6">
            <%= form.text_field :name, for: "name", class: "form-control", autofocus: true, autocomplete: "name", placeholder: "Enter Category Name", required: true %>
          </div>
        </div>      
      </div>
    </div>
    
    <div class="row justify-content-center my-4"> 
      <div class="col-2">
        <strong><%= form.submit( yield(:button_text),{ class: "btn btn-primary btn-md btn-block", data:{disable_with: "saving..."}})%></strong>
      </div>
    </div>
  </div>
<% end %>

app/views/food_categories/edit.html.erb
<% provide(:card_header, "Edit Category")%>
<% provide(:button_text, "Update")%>
<%= render "form" %>

app/views/food_categories/index.html.erb
<div class="card p-4 col-6 offset-3">
  <h3><i class="fa fa-tags" aria-hidden="true"></i> Food Categories</h3>

  <hr/>

  <table class="table table-borderless">
    <thead>
      <tr>
        <th>S.No:</th>
        <th>Category Name</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each_with_index do |category,i|%>
        <tr>
          <td><%= i+1 %></td>
          <td><%= category.name %></td>
          <td>
            <%= edit_link(edit_food_category_path(category.id)) %>
            <%= delete_link(food_category_path(category.id)) %>
          </td>
        </tr>      
      <% end %>
    </tbody>
  </table>

  <hr/>
  
  <div class="text-center">
    <%= link_to "New Category", new_food_category_path, class: "btn btn-primary", title: "Create new category" %>
  </div>
</div>

app/views/food_categories/new.html.erb
<% provide(:card_header, "Create new food category")%>
<% provide(:button_text, "Save")%>
<%= render "form" %>